import java.awt.*; 
import java.awt.event.*; 
import javax.swing.*; 

public class CheckBoxDemo implements ItemListener { 
   JLabel jlabSelected; 
   JLabel jlabChanged; 
   JCheckBox jcbAlpha; 
   JCheckBox jcbBeta; 
   JCheckBox jcbGamma; 

   CheckBoxDemo() { 
      // Create a new JFrame container. 
      JFrame frame = new JFrame("Demonstrate Check Boxes"); 
      // Specify FlowLayout for the layout manager. 
      frame.setLayout(new FlowLayout()); 
      // Give the frame an initial size. 
      frame.setSize(280, 120); 
      // Create empty labels. 
      jlabSelected = new JLabel(""); 
      jlabChanged = new JLabel(""); 
      // Make check boxes. 
      jcbAlpha = new JCheckBox("Alpha"); 
      jcbBeta = new JCheckBox("Beta"); 
      jcbGamma = new JCheckBox("Gamma");
      // Events generated by the check boxes 
      // are handled in common by the itemStateChanged() 
      // method implemented by CBDemo. 
      jcbAlpha.addItemListener(this); 
      jcbBeta.addItemListener(this); 
      jcbGamma.addItemListener(this); 
      // Add checkboxes and labels to the content pane. 
      frame.add(jcbAlpha); 
      frame.add(jcbBeta); 
      frame.add(jcbGamma); 
      frame.add(jlabChanged); 
      frame.add(jlabSelected); 
      // Display the frame. 
      frame.setVisible(true); 
} 

// This is the handler for the check boxes. 
public void itemStateChanged(ItemEvent ie) { 
   String str = ""; 
   // Obtain a reference to the check box that 
   // caused the event. 
   JCheckBox cb = (JCheckBox) ie.getItem(); 
   // Report what check box changed. 
   if(cb.isSelected()) 
      jlabChanged.setText(cb.getText() + " was just selected."); 
   else 
      jlabChanged.setText(cb.getText() + " was just cleared."); 
   // Report all selected boxes. 
   if(jcbAlpha.isSelected()) { 
      str += "Alpha "; 
   } 
   if(jcbBeta.isSelected()) { 
      str += "Beta "; 
   } 
   if(jcbGamma.isSelected()) { 
      str += "Gamma"; 
   } 
   jlabSelected.setText("Selected check boxes: " + str); 
 } 
}
